name: Build Docker Image (Release)

on:
  push:
    # trigger on version tag push
    tags:
      - "v*"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Metadata: Git"
        id: git-meta
        shell: bash
        run: |
          export TRUNCATED_GITHUB_SHA=$(echo ${{ github.sha }} | cut -c1-7);
          export VERSION=${GITHUB_REF/refs\/tags\//};
          echo "::set-output name=minisha::${TRUNCATED_GITHUB_SHA}";
          echo "::set-output name=version::${VERSION}";
          echo "::set-output name=versionlabel::${VERSION}+${TRUNCATED_GITHUB_SHA}"
      
      - name: "Docker: Setup Buildx"
        uses: docker/setup-buildx-action@v2
      
      - name: "Docker: Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: "Docker: Metadata"
        id: dockermeta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/GalvinGao/connchk
          tags: |
            type=semver,pattern=v{{version}}
            type=ref,event=branch
            type=ref,event=pr
          flavor: |
            latest=auto
      
      - name: "Docker: Build and Push Image"
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.dockermeta.outputs.tags }}
          labels: ${{ steps.dockermeta.outputs.labels }}
